name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Configuration
      run: |
        echo "source_url=https://github.com/crdroidandroid/android_kernel_oneplus_sm8250" >> $GITHUB_ENV
        echo "kernel_branch=16.0" >> $GITHUB_ENV
        echo "source_name=android_kernel_oneplus_sm8250" >> $GITHUB_ENV
        echo "KERNEL_CONFIG=vendor/combined_defconfig" >> $GITHUB_ENV

    - name: Check Configuration
      run: |
        echo 'kernel_branch:'"${{ env.kernel_branch }}" ; echo ' source_url:'"${{ env.source_url }}"   ; 
        echo 'source_name:' ${{ env.source_name }}  ; echo ' defconfig:'  ${{ env.KERNEL_CONFIG }}

    - name: Remove unused packages
      if: env.REMOVE_UNUSED_PACKAGES == 'true'
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: false
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: false

    - name: Set swap to 8G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 8

    - name: Setup build kernel environment
      run: |
        echo 'kernel_branch:'"${{ env.kernel_branch }}" ; echo ' source_url:'"${{ env.source_url }}"   ; 
        echo 'source_name:' ${{ env.source_name }}  ; echo ' defconfig:'  ${{ env.KERNEL_CONFIG }}
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y-%m-%d_%H-%M")" 
        echo "DEVICE=$(echo ${{ env.KERNEL_CONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//')" 
        sudo apt-get update
        sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3
        mkdir -p $GITHUB_WORKSPACE/Kernel

    - name: Download Clang
      run: |
        cd $GITHUB_WORKSPACE/Kernel
        mkdir toolchains && cd toolchains
        git clone --depth=1 https://github.com/EmanuelCN/zyc_clang-14.git zyc-clang

    - name: Download kernel source
      run: |
        cd $GITHUB_WORKSPACE/Kernel        
        git clone -b ${{ env.kernel_branch }} --depth=1 ${{ env.source_url }} ${{ env.source_name }}
        cat ./${{ env.source_name }}/arch/arm64/configs/vendor/kona-perf_defconfig ./${{ env.source_name }}/arch/arm64/configs/vendor/oplus.config > ./${{ env.source_name }}/arch/arm64/configs/vendor/${{ env.KERNEL_CONFIG }}

    - name: Setup KernelSU
      #if: env.ENABLE_KERNELSU == 'true'
      run: |
        cd $GITHUB_WORKSPACE/Kernel/${{ env.source_name }}
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
        KSU_VERSION=$(cd KernelSU && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
        echo "UPLOADNAME=-KernelSU_$KSU_VERSION"
        sed -i 's/# CONFIG_KSU is not set/CONFIG_KSU=y/g' arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        sed -i 's/CONFIG_KSU=n/CONFIG_KSU=y/g' arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        echo "CONFIG_MODULES=y" >> arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        echo "CONFIG_KPROBES=y" >> arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        cat ./arch/arm64/configs/vendor/${{ env.KERNEL_CONFIG }} |grep -i kprobe ; sleep 3


    - name: Setup ccache
      if: env.ENABLE_CCACHE == 'true'
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build-kernel-${{ env.DEVICE }}${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}
        max-size: 2G

   
    - name: Download Anykernel3
      run: |
        cd $GITHUB_WORKSPACE/Kernel/${{ env.source_name }}
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git

        

        
    - name: Build kernel
      run: |
        cd $GITHUB_WORKSPACE/Kernel/${{ env.source_name }}
        chmod +x ./build.sh ;  ./build.sh

        
    - name: Upload AnyKernel3
      #if: env.CHECK_FILE_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: instantnoodlep.zip
        path: Kernel/*.zip



